In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
from utils import agop_gcnn as agc
from utils import trainer as tr
from torch.utils.data import Dataset
import random
import torch.backends.cudnn as cudnn
#import rfm
import numpy as np
from trained_models.CIFAR.model2 import trainer as t
import numpy as np
from sklearn.model_selection import train_test_split
from torch.linalg import norm
from torchvision import models
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
from utils.groupy.gconv.pytorch_gconv.splitgconv2d import P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M
from groupy.gconv.make_gconv_indices import *
from copy import deepcopy
from torch.nn.functional import pad
from torch.func import jacrev

Setting up a new session...
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.


In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
#device='cpu'
print(f"Using device: {device}")


Using device: cuda:0


In [4]:
!nvidia-smi

Tue Aug 12 13:16:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    On  |   00000000:03:00.0 Off |                  N/A |
|  0%   41C    P8             11W /  320W |      18MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
torch.cuda.empty_cache()

In [3]:
trainloader, valloader, testloader, init_net, net = t.train_net()

Files already downloaded and verified
Files already downloaded and verified
Model weights loaded successfully.


In [4]:
#tr.visualize_predictions(net, testloader, range(10), device, num_images=36)
print(tr.get_acc_ce(net.to(device), testloader))

90.14


In [9]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=0, max_batches=10)

l_idx 0
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([27, 27])
Correlation between Initial and Trained CNFM:  tensor(0.4908, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.4601, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.6740, device='cuda:0', grad_fn=<DivBackward0>)


In [10]:
d= agc.verify_NFA(net, init_net, trainloader, layer_idx=1,max_batches=10)

l_idx 3
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([1656, 1656])
Correlation between Initial and Trained CNFM:  tensor(0.0141, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0167, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.8659, device='cuda:0', grad_fn=<DivBackward0>)


In [11]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=2,max_batches=10)

l_idx 4
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([1656, 1656])
Correlation between Initial and Trained CNFM:  tensor(0.0151, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.6499, device='cuda:0', grad_fn=<DivBackward0>)


tensor([[ 0.0166,  0.0125,  0.0134,  ..., -0.0067, -0.0075, -0.0064],
        [ 0.0112,  0.0358,  0.0108,  ..., -0.0002, -0.0045, -0.0007],
        [ 0.0135,  0.0065,  0.0230,  ..., -0.0126, -0.0095, -0.0118],
        ...,
        [-0.0069, -0.0004, -0.0126,  ...,  0.0476,  0.0310,  0.0413],
        [-0.0081, -0.0045, -0.0096,  ...,  0.0309,  0.0405,  0.0314],
        [-0.0066, -0.0008, -0.0116,  ...,  0.0410,  0.0315,  0.0452]])

In [12]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=3, max_batches=10)

l_idx 5
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([1656, 1656])
Correlation between Initial and Trained CNFM:  tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9044, device='cuda:0', grad_fn=<DivBackward0>)


tensor([[ 0.0085,  0.0049,  0.0051,  ...,  0.0016, -0.0006,  0.0019],
        [ 0.0109,  0.0153,  0.0094,  ...,  0.0019, -0.0019,  0.0030],
        [ 0.0058,  0.0068,  0.0116,  ...,  0.0011,  0.0010,  0.0023],
        ...,
        [ 0.0019,  0.0017,  0.0010,  ...,  0.0193,  0.0193,  0.0172],
        [-0.0008, -0.0019,  0.0011,  ...,  0.0195,  0.0258,  0.0189],
        [ 0.0018,  0.0030,  0.0024,  ...,  0.0172,  0.0189,  0.0191]])

In [13]:
agc.verify_NFA(net, init_net, trainloader, layer_idx=4, max_batches=10)

l_idx 6
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([1656, 1656])
Correlation between Initial and Trained CNFM:  tensor(0.0430, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0520, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9446, device='cuda:0', grad_fn=<DivBackward0>)


tensor([[2.7254e-03, 1.8548e-03, 1.1986e-03,  ..., 2.0643e-04, 1.0479e-03,
         1.3902e-03],
        [1.5546e-03, 1.0969e-03, 1.2655e-03,  ..., 9.2472e-04, 1.0952e-03,
         9.0818e-04],
        [1.2924e-03, 1.5548e-03, 2.5623e-03,  ..., 1.3227e-03, 7.9072e-04,
         5.9559e-06],
        ...,
        [2.7053e-04, 9.7803e-04, 1.3198e-03,  ..., 1.4313e-02, 8.0339e-03,
         5.4103e-04],
        [1.1162e-03, 1.1044e-03, 7.7432e-04,  ..., 8.0061e-03, 1.3394e-02,
         7.8283e-03],
        [1.5228e-03, 8.7594e-04, 2.5585e-05,  ..., 5.4939e-04, 7.8600e-03,
         1.4090e-02]])

In [14]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=5, max_batches=10)

l_idx 7
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([3240, 3240])
Correlation between Initial and Trained CNFM:  tensor(0.0122, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0137, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9446, device='cuda:0', grad_fn=<DivBackward0>)


tensor([[ 3.9763e-03,  2.3287e-03,  9.8365e-04,  ...,  4.8979e-04,
         -5.2403e-06,  1.4579e-04],
        [ 2.2689e-03,  2.6656e-03,  1.1901e-03,  ...,  5.1787e-04,
          3.4850e-04,  3.3991e-04],
        [ 9.9668e-04,  1.2291e-03,  2.3380e-03,  ...,  5.0076e-04,
          4.5884e-04,  5.0870e-04],
        ...,
        [ 4.9448e-04,  5.1970e-04,  5.1167e-04,  ...,  5.4827e-04,
          3.8938e-04,  3.5175e-04],
        [-4.7210e-05,  3.5642e-04,  4.7247e-04,  ...,  3.9221e-04,
          6.2030e-04,  4.7704e-04],
        [ 2.0480e-04,  3.4119e-04,  4.9801e-04,  ...,  3.5738e-04,
          4.7325e-04,  5.3752e-04]])

In [15]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=6, max_batches=10)

l_idx 8
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([3240, 3240])
Correlation between Initial and Trained CNFM:  tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.8924, device='cuda:0', grad_fn=<DivBackward0>)


In [16]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=7, max_batches=10)

l_idx 9
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([3240, 3240])
Correlation between Initial and Trained CNFM:  tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9246, device='cuda:0', grad_fn=<DivBackward0>)


In [17]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=8, max_batches=10)

l_idx 10
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([3240, 3240])
Correlation between Initial and Trained CNFM:  tensor(0.0555, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0632, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9455, device='cuda:0', grad_fn=<DivBackward0>)


In [18]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=9, max_batches=10)

l_idx 11
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([6552, 6552])
Correlation between Initial and Trained CNFM:  tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9327, device='cuda:0', grad_fn=<DivBackward0>)


In [19]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=10, max_batches=10)

l_idx 12
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([6552, 6552])
Correlation between Initial and Trained CNFM:  tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9517, device='cuda:0', grad_fn=<DivBackward0>)


In [20]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=11, max_batches=10)

l_idx 13
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([6552, 6552])
Correlation between Initial and Trained CNFM:  tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9301, device='cuda:0', grad_fn=<DivBackward0>)


In [21]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=12, max_batches=10)

l_idx 14
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([6552, 6552])
Correlation between Initial and Trained CNFM:  tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9330, device='cuda:0', grad_fn=<DivBackward0>)


In [22]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=13, max_batches=10)

l_idx 15
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([6552, 6552])
Correlation between Initial and Trained CNFM:  tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9121, device='cuda:0', grad_fn=<DivBackward0>)


In [23]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=14, max_batches=10)

l_idx 16
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([6552, 6552])
Correlation between Initial and Trained CNFM:  tensor(0.0641, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0796, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.9411, device='cuda:0', grad_fn=<DivBackward0>)


In [24]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=15, max_batches=10)

l_idx 17
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([13032, 13032])
Correlation between Initial and Trained CNFM:  tensor(0.0490, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0605, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.8770, device='cuda:0', grad_fn=<DivBackward0>)


In [25]:
d=agc.verify_NFA(net, init_net, trainloader, layer_idx=16, max_batches=10)

l_idx 18
Computing GOP for sample 0 out of 10
Computing GOP for sample 1 out of 10
Computing GOP for sample 2 out of 10
Computing GOP for sample 3 out of 10
Computing GOP for sample 4 out of 10
Computing GOP for sample 5 out of 10
Computing GOP for sample 6 out of 10
Computing GOP for sample 7 out of 10
Computing GOP for sample 8 out of 10
Computing GOP for sample 9 out of 10
Computing GOP for sample 10 out of 10
Shape after gradients:  torch.Size([13032, 13032])
Correlation between Initial and Trained CNFM:  tensor(0.0158, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Initial CNFM and Trained AGOP:  tensor(0.0183, device='cuda:0', grad_fn=<DivBackward0>)
Correlation between Trained CNFM and Trained AGOP:  tensor(0.8427, device='cuda:0', grad_fn=<DivBackward0>)


# Debug: Agop verification for Resnet Gcnn

In [7]:
''' This module does the following
1. Scan the network for conv layers
2. For each gcnn conv layer compute W^TW of eq 3
3. For each gcnn conv layer compute the AGOP(AJOP in case of multiple outputs)
4. For each gcnn conv layer print the pearson correlation between 2 and 3
'''

import torch
import torch.nn as nn
import random
import numpy as np
from torch.func import jacrev
from torch.nn.functional import pad
from torch.linalg import norm, svd
from torchvision import models
import visdom
from torch.linalg import norm, eig
import random
import torch.backends.cudnn as cudnn
from torch.linalg import norm
from torchvision import models
import torch.nn.functional as F
from utils.groupy.gconv.pytorch_gconv.splitgconv2d import P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M
from trained_models.CIFAR.model2.model2 import BasicBlock, Bottleneck
from groupy.gconv.make_gconv_indices import *
from copy import deepcopy

SEED = 2323

torch.manual_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.cuda.manual_seed(SEED)

vis = visdom.Visdom('http://127.0.0.1', use_incoming_socket=False)
vis.close(env='main')

def patchify(x, in_channels, ip_stab, patch_size, stride_size, padding=None, pad_type='zeros'):
    '''
        Given an input image (n,c,h,w) generate (n,w_out,h_out,c,q,s) respecting stride,padding, 
        w_out is number of pathces along the width for the given stride after padding
        h_out is number of pathces along the height for the given stride after padding
        (q,s) is the kernel dimensions 
    '''
    input_shape = x.size()
    #TODO: The last two shapes look swapped. This was the same order in cohens code too. For square ips 
    #there is no effect. However for rect ips what would happen?
    x = x.view(input_shape[0], in_channels*ip_stab, input_shape[-2], input_shape[-1])
    #x = x.view(input_shape[0], in_channels*ip_stab, input_shape[-2], input_shape[-1])
    q1, q2 = patch_size
    s1, s2 = stride_size
    #print("Image Shape",x.shape)
    if padding is None:
        pad_1 = (q1-1)//2
        pad_2 = (q2-1)//2
    else:
        pad_1, pad_2 = padding

    pad_dims = (pad_2, pad_2, pad_1, pad_1)
    if pad_type == 'zeros':
        x = pad(x, pad_dims)
    elif pad_type == 'circular':
        x = pad(x, pad_dims, 'circular')
        
    patches = x.unfold(2, q1, s1).unfold(3, q2, s2) #(n, c, h_out, w_out, q, s)
    #print("Image Shape1",patches.shape)
    patches = patches.transpose(1, 3).transpose(1, 2) #(n,w_out,h_out,c,q,s) 
    #print("Image Shape2",patches.shape)
    return patches

def trans_filter(w, inds):
    inds_reshape = inds.reshape((-1, inds.shape[-1])).astype(np.int64)
    w_indexed = w[:, :, inds_reshape[:, 0].tolist(), inds_reshape[:, 1].tolist(), inds_reshape[:, 2].tolist()]
    w_indexed = w_indexed.view(w_indexed.size()[0], w_indexed.size()[1],
                                    inds.shape[0], inds.shape[1], inds.shape[2], inds.shape[3])
    w_transformed = w_indexed.permute(0, 2, 1, 3, 4, 5)
    return w_transformed.contiguous()
    
class PatchConvLayer(nn.Module):
    def __init__(self, conv_layer):
        super().__init__()
        self.layer = conv_layer #(k,c,q,s)
        #inds = make_c4_z2_indices(self.layer.ksize)
       
    def forward(self, patches):
        if(len(patches.shape)==7)
            patches= patches[:,0,:,:,:,:,:]
        tw = trans_filter(self.layer.weight, self.layer.inds)
        tw_shape = (self.layer.out_channels * self.layer.output_stabilizer_size,
                    self.layer.in_channels * self.layer.input_stabilizer_size,
                    self.layer.ksize, self.layer.ksize)
        tw = tw.view(tw_shape)
        #print("tw shape",tw.shape)
        #print("Patch_shape", patches.shape)
        out = torch.einsum('nhwcqr, kcqr -> nhwk', patches, tw)
        n, w, h, k = out.shape
        out = out.transpose(1, 3).transpose(2, 3) #(n,k,h_out,w_out)
        out = out.view(n, self.layer.out_channels, self.layer.output_stabilizer_size, h, w)
        #print("out_shape", out.shape)
        return out


class PatchBasicBlock(nn.Module):

    def __init__(self, block_layer):
        super().__init__()
        self.layer = block_layer

    def forward(self, X):          
        print(X.shape)
        x1 = X[:,0,:,:,:,:,:] #(1,w_out, h_out, c, q, s)
        x2 = X[:,1,:,:,:,:,:] #(1,w_out, h_out, c, q, s)
        o = self.layer.features(x1)
        if(self.layer.shortcut):
            z = self.layer.shortcut(x2)
            o+=z
        o = self.layer.lrelu(o)
        return o
        
    

def get_jacobian(net, data, c_idx=0, chunk=100):
    with torch.no_grad():
        def single_net(X):
            # x is (2, w_out,h_out,c,q,s)
            return net(X.unsqueeze(0))[:,c_idx*chunk:(c_idx+1)*chunk].squeeze(0)
        # Parallelize across the images.
        #data: (n, 2, w_out, h_out, c, q, s)
        return torch.vmap(jacrev(single_net))(data) #(n, chunk, 2, w_out, h_out, c, q, s)

def egop(model, z, classes=10, chunk_idxs=10):
    ajop = 0
    c = classes
    #Chunking is done to compute jacobian as sum of smaller size matrices using outer product. This saves memory
    chunk = c // chunk_idxs
    for i in range(chunk_idxs):
        J = get_jacobian(model, z, c_idx=i, chunk=chunk) #(n, chunk, 2, w_out, h_out, c, q, s)
        J= J[:,:,0,:,:,:,:,:]
        n, c, w, h, _, _, _ = J.shape
        J = J.transpose(1, 3).transpose(1, 2) #(n, w_out, h_out, chunk, c, q, s)
        grads = J.reshape(n*w*h, c, -1) #(n*w_out*h_out, chunk, c*q*s)
        #Clarify: Where is mean taken
        ajop += torch.einsum('ncd, ncD -> dD', grads, grads) #(c*q*s,c*q*s)
        del J, grads
        torch.cuda.empty_cache()
    return ajop


def load_nn(net, init_net, layer_idx=0):
    
    count = 0
    # Get the layer_idx+1 th conv layer
    for idx, m in enumerate(net.features):
        if isinstance(m, (P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M, BasicBlock, Bottleneck)):
            count += 1
        if count-1 == layer_idx:
            l_idx = idx
            break

    print("l_idx",l_idx)
    if(isinstance(net.features[l_idx],(P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M))):
        
        # Construct patchnet
        patchnet = deepcopy(net)
        temp = deepcopy(net.features[l_idx])
        conv_layer = PatchConvLayer(temp)
        
        #Truncate all layers before l_idx    
        patchnet.features = net.features[l_idx:]
        patchnet.features[0] = conv_layer
        
        #layer whose CNFM we need
        layer = deepcopy(net.features[l_idx])
        layer_init = deepcopy(init_net.features[l_idx])     
        
    else:   
        
        # Construct patchnet
        patchnet = deepcopy(net)
        temp_block = deepcopy(net.features[l_idx])
        conv_layer = PatchConvLayer(temp_block.features[0])
        temp_block.features[0]= conv_layer
        if(len(temp_block.shortcut)>0):
           short_layer = PatchConvLayer(temp_block.shortcut[0])
           temp_block.shortcut[0] = short_layer
        else:
           temp_block.shortcut= None
            
        temp_block = PatchBasicBlock(temp_block)
        
        #Truncate all layers before l_idx    
        patchnet.features = net.features[l_idx:]
        patchnet.features[0] = temp_block
        
        #layer whose CNFM we need
        layer = deepcopy(net.features[l_idx].features[0])
        layer_init = deepcopy(init_net.features[l_idx].features[0])        
    
    # Extract all the meta info of the current conv layer.
    (q, s) = layer.kernel_size
    (pad1, pad2) = layer.padding
    (s1, s2) = layer.stride 
    in_channels = layer.in_channels
    input_stabilizer_size = layer.input_stabilizer_size
    
    # Extract W matrix
    tw = trans_filter(layer.weight, layer.inds)
    tw_shape = (layer.out_channels * layer.output_stabilizer_size,
                        layer.in_channels * layer.input_stabilizer_size,
                        layer.ksize, layer.ksize)
    M = tw.view(tw_shape)
    
    tw= trans_filter(layer_init.weight, layer_init.inds)
    tw_shape = (layer_init.out_channels * layer_init.output_stabilizer_size,
                        layer_init.in_channels * layer_init.input_stabilizer_size,
                        layer_init.ksize, layer_init.ksize)
    M0 = tw.view(tw_shape)
    
    k, ki, q,s= M.shape
                
    # Build W which is a (k, c*q*s) matrix. What to do with ip_stab
    M = M.reshape(-1, ki*q*s)
                
    # Compute WtW which is (c*q*s,c*q*s) matrix
    M = torch.einsum('nd, nD -> dD', M, M)

    k, ki, q,s= M0.shape

    # Build W which is a (k, c*q*s) matrix. What to do with ip_stab
    M0 = M0.reshape(-1, ki*q*s)

    # Compute WtW which is (c*q*s,c*q*s) matrix
    M0 = torch.einsum('nd, nD -> dD', M0, M0)

    return net, patchnet, M, M0, l_idx, [(q, s), (pad1,pad2), (s1,s2)], in_channels, input_stabilizer_size


def get_grads(net, in_channels, input_stabilizer_size, patchnet, trainloader,
              kernel=(3,3), padding=(1,1),
              stride=(1,1), layer_idx=0, max_batches=2, classes=10, chunk_size=10):
    net.eval()
    net.cuda()
    patchnet.eval()
    patchnet.cuda()
    M = 0
    q, s = kernel
    pad1, pad2 = padding
    s1, s2 = stride
    for idx, batch in enumerate(trainloader):
        print("Computing GOP for sample " + str(idx) + \
              " out of " + str(max_batches))
        imgs, _ = batch
        #imgs= imgs.double()
        with torch.no_grad():
            imgs = imgs.cuda()        
            # Run the first half of the network wrt to the current layer 
            imgs = net.features[:layer_idx](imgs).cpu() #(n,c,h,w)
        patches = patchify(imgs, in_channels, input_stabilizer_size, 
                           (q, s), (s1,s2), padding=(pad1,pad2))#(n,w_out,h_out,c,q,s)
        p_copy = deepcopy(patches)
        patches = patches.cuda()
        p_copy = p_copy.cuda()
        c_patches = torch.stack([patches, p_copy], dim=1) #(n,2,w_out,h_out,c,q,s)
        M += egop(patchnet, c_patches, classes, chunk_size).cpu()
        del imgs, patches, p_copy, c_patches
        torch.cuda.empty_cache()
        if idx >= max_batches:
            break
    net.cpu()
    patchnet.cpu()
    return M


def min_max(M):
    return (M - M.min()) / (M.max() - M.min())


def correlation(A, B):
    M1 = A.clone()
    M2 = B.clone()
    M1 -= M1.mean()
    M2 -= M2.mean()

    norm1 = norm(M1.flatten())
    norm2 = norm(M2.flatten())

    return torch.sum(M1.cuda() * M2.cuda()) / (norm1 * norm2)


def verify_NFA(net, init_net, trainloader, layer_idx=0, max_batches=2, classes=10, chunk_size=10):

    #net = net.double()
    #init_net = init_net.double()
    net, patchnet, M, M0, l_idx, conv_vals, in_channels, input_stabilizer_size = load_nn(net,
                                                     init_net,
                                                     layer_idx=layer_idx)
    (q, s), (pad1, pad2), (s1, s2) = conv_vals
  

    G = get_grads(net, in_channels, input_stabilizer_size, patchnet, trainloader,
                  kernel=(q, s),
                  padding=(pad1, pad2),
                  stride=(s1, s2),
                  layer_idx=l_idx, max_batches=2, classes=10, chunk_size=10)
    
    print("Shape after gradients: ", G.shape)
    G = sqrt(G)
    Gop = G.clone()
    
    print("Correlation between Initial and Trained CNFM: ", correlation(M0, M))
    print("Correlation between Initial CNFM and Trained AGOP: ", correlation(M0, G))
    print("Correlation between Trained CNFM and Trained AGOP: ", correlation(M, G))

    #print("Final: ", i_val, r_val)
    return Gop 
    #return i_val.data.numpy(), r_val.data.numpy()



def sqrt(G):
    U, s, Vt = svd(G)
    s = torch.pow(s, 1./2)
    G = U @ torch.diag(s) @ Vt
    return G


#TODO: ADD a visualizer for the image

#if __name__ == "__main__":
    #main()

Setting up a new session...
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.


In [9]:
verify_NFA(net, init_net, trainloader, layer_idx=2)

l_idx 4
Computing GOP for sample 0 out of 2
yo torch.Size([128, 2, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 32, 32, 184, 3, 3])
torch.Size([1, 2, 32, 32, 184, 3, 3])
torch.Size([128, 1, 2, 32, 3

tensor([[ 9.5248e-03,  9.7290e-03,  7.0976e-03,  ..., -3.4146e-03,
         -3.8969e-03, -3.3975e-03],
        [ 8.6367e-03,  8.0289e-03,  2.3470e-03,  ..., -1.7982e-04,
         -2.3678e-03, -4.8670e-04],
        [ 5.9357e-03,  4.0570e-03,  1.2625e-02,  ..., -6.6905e-03,
         -5.2449e-03, -6.1110e-03],
        ...,
        [-3.1580e-03, -1.5815e-05, -6.6168e-03,  ...,  2.4197e-02,
          1.6336e-02,  2.1386e-02],
        [-3.9028e-03, -2.2616e-03, -5.0200e-03,  ...,  1.6322e-02,
          2.0512e-02,  1.6485e-02],
        [-3.1120e-03, -4.2242e-04, -6.0089e-03,  ...,  2.1491e-02,
          1.6569e-02,  2.3166e-02]])

In [11]:
verify_NFA(net, init_net, trainloader, layer_idx=4)

l_idx 6
Computing GOP for sample 0 out of 2
yo torch.Size([128, 2, 16, 16, 184, 3, 3])
torch.Size([1, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 16, 16, 184, 3, 3])
torch.Size([1, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 16, 16, 184, 3, 3])
Computing GOP for sample 1 out of 2
yo torch.Size([128, 2, 16, 16, 184, 3, 3])
torch.Size([1, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 16, 16, 184, 3, 3])
torch.Size([1, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 16, 16, 184, 3, 3])
Computing GOP for sample 2 out of 2
yo torch.Size([128, 2, 16, 16, 184, 3, 3])
torch.Size([1, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 16, 16, 184, 3, 3])
torch.Size([1, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 2, 16, 16, 184, 3, 3])
torch.Size([128, 5, 16, 16, 184, 3, 3])
Shape after gradients:  torch

tensor([[ 1.2816e-03,  7.5665e-04,  6.2645e-04,  ...,  1.2684e-04,
          5.6993e-04,  7.7317e-04],
        [ 6.8209e-04,  1.3099e-03,  9.5193e-04,  ...,  5.1605e-04,
          6.0238e-04,  4.8448e-04],
        [ 6.9021e-04,  7.7224e-04,  1.4948e-03,  ...,  7.0169e-04,
          4.0642e-04, -1.7308e-05],
        ...,
        [ 1.2271e-04,  5.0140e-04,  7.0754e-04,  ...,  7.4797e-03,
          4.2182e-03,  2.7374e-04],
        [ 5.9704e-04,  5.7623e-04,  4.1070e-04,  ...,  4.2437e-03,
          7.0327e-03,  4.1387e-03],
        [ 7.4970e-04,  4.5896e-04,  4.6176e-06,  ...,  2.8718e-04,
          4.1604e-03,  7.3998e-03]])

In [8]:
verify_NFA(net, init_net, trainloader, layer_idx=5)

l_idx 7
Computing GOP for sample 0 out of 2
yo torch.Size([128, 2, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 1

tensor([[ 1.9970e-03,  1.0795e-03,  5.2341e-04,  ...,  2.5473e-04,
         -1.1331e-05,  9.3032e-05],
        [ 1.1562e-03,  1.3004e-03,  7.0936e-04,  ...,  2.7527e-04,
          1.8115e-04,  1.7495e-04],
        [ 5.1795e-04,  6.5022e-04,  1.1698e-03,  ...,  2.7021e-04,
          2.4670e-04,  2.6369e-04],
        ...,
        [ 2.6430e-04,  2.7197e-04,  2.6816e-04,  ...,  3.0637e-04,
          2.0277e-04,  1.8298e-04],
        [-8.4667e-06,  1.7590e-04,  2.3936e-04,  ...,  2.0432e-04,
          3.3947e-04,  2.4344e-04],
        [ 8.4305e-05,  1.7609e-04,  2.6021e-04,  ...,  1.7653e-04,
          2.4072e-04,  2.9809e-04]])

In [10]:
verify_NFA(net, init_net, trainloader, layer_idx=6)

l_idx 8
Computing GOP for sample 0 out of 2
yo torch.Size([128, 2, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 16, 16, 360, 3, 3])
torch.Size([1, 2, 16, 16, 360, 3, 3])
torch.Size([128, 1, 2, 16, 1

tensor([[ 8.0130e-03,  3.1811e-03,  1.8338e-03,  ..., -3.8372e-04,
         -1.3576e-03, -7.1177e-04],
        [ 3.0714e-03,  3.3480e-03,  8.1271e-04,  ..., -1.4884e-04,
         -4.4777e-04, -3.2525e-05],
        [ 1.7831e-03,  7.4513e-04,  9.0855e-03,  ...,  4.1904e-04,
         -3.4318e-04, -3.2680e-04],
        ...,
        [-3.6510e-04, -1.4542e-04,  4.2135e-04,  ...,  5.8417e-04,
          4.8998e-04,  2.1349e-04],
        [-1.3459e-03, -4.4536e-04, -3.4720e-04,  ...,  4.9811e-04,
          1.1331e-03,  7.4355e-04],
        [-6.9700e-04, -3.7026e-05, -3.2442e-04,  ...,  2.0186e-04,
          7.4446e-04,  9.0367e-04]])