In [1]:
import torch
from trained_models.MNIST.model4 import trainer as t
from utils.rfm_gcnn import agop_gcnn as agc
from utils import trainer as tr

Current Path: /workspaces/DLR


In [2]:
# Get the Current Working Directory (where you ran the script)


In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
#device='cpu'
print(f"Using device: {device}")


Using device: cuda:0


In [3]:
torch.cuda.empty_cache()

In [4]:
trainloader, valloader, testloader, init_net, net = t.train_net(force_train=False)

Model Directory: /workspaces/DLR/trained_models/MNIST/model4/nn_models/
Model weights loaded successfully.


In [5]:
#TODO: Fix the log_softmax user warning.
print(tr.get_acc_ce(net.to(device), testloader))

99.25


In [6]:
agc.verify_NFA(net, init_net, trainloader, layer_idx=0, centering = False)

l_idx 0
************* Chunk0*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk1*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk2*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk3*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk4*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk5*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk6*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64

(tensor([[ 0.5045,  0.1734, -0.0089,  0.2363,  0.1476, -0.1291, -0.0185, -0.1303,
          -0.2174],
         [ 0.1734,  0.6396,  0.2541, -0.0385,  0.1716, -0.0145, -0.1622, -0.1935,
          -0.1207],
         [-0.0089,  0.2541,  0.5411, -0.1441,  0.1502,  0.1912, -0.2563, -0.1612,
          -0.0096],
         [ 0.2363, -0.0385, -0.1441,  0.6345,  0.1729, -0.1858,  0.1913, -0.0202,
          -0.1452],
         [ 0.1476,  0.1716,  0.1502,  0.1729,  0.9842,  0.1731,  0.1479,  0.1745,
           0.1455],
         [-0.1291, -0.0145,  0.1912, -0.1858,  0.1731,  0.6275, -0.1471, -0.0475,
           0.2280],
         [-0.0185, -0.1622, -0.2563,  0.1913,  0.1479, -0.1471,  0.5457,  0.2664,
          -0.0138],
         [-0.1303, -0.1935, -0.1612, -0.0202,  0.1745, -0.0475,  0.2664,  0.6554,
           0.1767],
         [-0.2174, -0.1207, -0.0096, -0.1452,  0.1455,  0.2280, -0.0138,  0.1767,
           0.5018]]),
 tensor(0.9713, device='cuda:0', dtype=torch.float64, grad_fn=<DivBackward0>))

In [7]:
agc.verify_NFA(net, init_net, trainloader, layer_idx=1, centering = False)

l_idx 2
************* Chunk0*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
************* Chunk1*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
************* Chunk2*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
************* Chunk3*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
************* Chunk4*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
************* Chunk5*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3, 3])
************* Chunk6*************
torch.Size([64, 1, 24, 24, 40, 3, 3])
torch.Size([64, 1, 24, 24, 40, 3

(tensor([[ 0.0218,  0.0077,  0.0016,  ..., -0.0051,  0.0018, -0.0070],
         [ 0.0077,  0.0252,  0.0031,  ...,  0.0032,  0.0008, -0.0042],
         [ 0.0016,  0.0031,  0.0270,  ..., -0.0086, -0.0052, -0.0085],
         ...,
         [-0.0051,  0.0032, -0.0086,  ...,  0.0488,  0.0113, -0.0008],
         [ 0.0018,  0.0008, -0.0052,  ...,  0.0113,  0.0310,  0.0129],
         [-0.0070, -0.0042, -0.0085,  ..., -0.0008,  0.0129,  0.0406]]),
 tensor(0.9761, device='cuda:0', dtype=torch.float64, grad_fn=<DivBackward0>))

In [8]:
agc.verify_NFA(net, init_net, trainloader, layer_idx=2)

l_idx 5
************* Chunk0*************


torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
************* Chunk1*************
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
************* Chunk2*************
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
************* Chunk3*************
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
************* Chunk4*************
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
************* Chunk5*************
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
************* Chunk6*************
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3])
torch.Size([64, 1, 10, 10, 40, 3, 3]

(tensor([[ 2.0180e-02,  1.5503e-03, -3.9504e-03,  ..., -4.4463e-04,
          -2.2673e-03,  2.3493e-03],
         [ 1.5503e-03,  1.8067e-02, -3.7783e-03,  ...,  3.3839e-03,
          -3.2722e-05,  7.2747e-04],
         [-3.9504e-03, -3.7783e-03,  1.7385e-02,  ..., -1.8005e-03,
           1.9659e-04, -7.4279e-04],
         ...,
         [-4.4463e-04,  3.3839e-03, -1.8005e-03,  ...,  2.0488e-02,
           1.7270e-04, -7.3151e-04],
         [-2.2673e-03, -3.2722e-05,  1.9659e-04,  ...,  1.7270e-04,
           1.8623e-02,  2.8832e-03],
         [ 2.3493e-03,  7.2747e-04, -7.4279e-04,  ..., -7.3151e-04,
           2.8832e-03,  1.9464e-02]]),
 tensor(0.9346, device='cuda:0', dtype=torch.float64, grad_fn=<DivBackward0>))

In [9]:
agc.verify_NFA(net, init_net, trainloader, layer_idx=3)

l_idx 7
************* Chunk0*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
************* Chunk1*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
************* Chunk2*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
************* Chunk3*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
************* Chunk4*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
************* Chunk5*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
************* Chunk6*************
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3])
torch.Size([64, 1, 8, 8, 80, 3, 3]

(tensor([[ 1.1643e-02, -9.5763e-05,  3.0502e-03,  ..., -1.2613e-03,
          -7.2507e-04,  6.8137e-04],
         [-9.5764e-05,  1.2183e-02,  4.7378e-04,  ..., -1.2417e-03,
           4.2897e-03,  1.3370e-03],
         [ 3.0502e-03,  4.7378e-04,  1.1721e-02,  ...,  5.5054e-04,
           4.6295e-04,  1.7678e-03],
         ...,
         [-1.2613e-03, -1.2417e-03,  5.5054e-04,  ...,  1.2312e-02,
           3.9534e-04, -4.1718e-04],
         [-7.2507e-04,  4.2897e-03,  4.6295e-04,  ...,  3.9534e-04,
           1.1025e-02, -2.8330e-04],
         [ 6.8137e-04,  1.3370e-03,  1.7678e-03,  ..., -4.1718e-04,
          -2.8330e-04,  1.0082e-02]]),
 tensor(0.9646, device='cuda:0', dtype=torch.float64, grad_fn=<DivBackward0>))

# Debug Task: Debug gcnn for AGOP

In [10]:
''' This module does the following
1. Scan the network for conv layers
2. For each gcnn conv layer compute W^TW of eq 3
3. For each gcnn conv layer compute the AGOP(AJOP in case of multiple outputs)
4. For each gcnn conv layer print the pearson correlation between 2 and 3
'''

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.func import jacrev
#from torch.nn.functional import pad
from torch.linalg import norm, svd, eig
from torchvision import models

import random
import numpy as np
import visdom
from copy import deepcopy

from utils.rfm_gcnn.utils import patchify, trans_filter, sqrt, matrix_power_eigendecomposition, correlation, min_max, get_nfm
from utils.groupy.gconv.pytorch_gconv.splitgconv2d import P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M
from groupy.gconv.make_gconv_indices import *


#Todo: Import these blocks directly by avoiding model2
from trained_models.CIFAR.model2.model2 import BasicBlock, Bottleneck
#from trained_models.MNIST.model4.model4 import BasicBlock, Bottleneck

SEED = 2323

torch.manual_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.cuda.manual_seed(SEED)

#vis = visdom.Visdom('http://127.0.0.1', use_incoming_socket=False)
#vis.close(env='main')


class PatchConvLayer(nn.Module):
    def __init__(self, conv_layer):
        super().__init__()
        self.layer = conv_layer #(k,c,q,s)
        #inds = make_c4_z2_indices(self.layer.ksize)
       
    def forward(self, patches):
        if(len(patches.shape)==7):
            patches= patches[:,0,:,:,:,:,:]
        tw = trans_filter(self.layer.weight, self.layer.inds)
        tw_shape = (self.layer.out_channels * self.layer.output_stabilizer_size,
                    self.layer.in_channels * self.layer.input_stabilizer_size,
                    self.layer.ksize, self.layer.ksize)
        tw = tw.reshape(tw_shape)
        #print("tw shape",tw.shape)
        #print("Patch_shape", patches.shape)
        out = torch.einsum('nhwcqr, kcqr -> nhwk', patches, tw)
        n, w, h, k = out.shape
        out = out.transpose(1, 3).transpose(2, 3) #(n,k,h_out,w_out)
        out = out.reshape(n, self.layer.out_channels, self.layer.output_stabilizer_size, h, w)
        #print("out_shape", out.shape)
        return out


class PatchBasicBlock(nn.Module):

    def __init__(self, block_layer):
        super().__init__()
        self.layer = block_layer

    def forward(self, X):          
        #print(X.shape)
        x1 = X[:,0,:,:,:,:,:] #(1,w_out, h_out, c, q, s)
        x2 = X[:,1,:,:,:,:,:] #(1,w_out, h_out, c, q, s)
        o = self.layer.features(x1)
        if(self.layer.shortcut):
            z = self.layer.shortcut(x2)
            o+=z
        o = self.layer.lrelu(o)
        return o
        
    

def get_jacobian(net, data, c_idx=0, chunk=100):
    with torch.no_grad():
        def single_net(X):
            # x is (2, w_out,h_out,c,q,s)
            return net(X.unsqueeze(0))[:,c_idx*chunk:(c_idx+1)*chunk].squeeze(0)
        # Parallelize across the images.
        #data: (bs, 2, w_out, h_out, c, q, s)
        return torch.vmap(jacrev(single_net))(data) #(bs, chunk, 2, w_out, h_out, c, q, s)


def egop(model, z, classes=10, chunk_idxs=10):
    ajop = 0
    c = classes
    #Chunking is done to compute jacobian as sum of smaller size matrices using outer product. This saves memory
    chunk = c // chunk_idxs
    chunk_list = []
    for i in range(chunk_idxs):
        J = get_jacobian(model, z, c_idx=i, chunk=chunk) #(n, chunk, 2, w_out, h_out, c, q, s)
        J= J[:,:,0,:,:,:,:,:]
        n, c, w, h, _, _, _ = J.shape
        J = J.transpose(1, 3).transpose(1, 2) #(n, w_out, h_out, chunk, c, q, s)
        grads = J.reshape(n*w*h, c, -1) #(n*w_out*h_out, chunk, c*q*s)
        chunk_list.append(grads)
        #Clarify: Where is mean taken      
        #ajop += torch.einsum('ncd, ncD -> dD', grads, grads) #(c*q*s,c*q*s)
        #del J, grads
        #torch.cuda.empty_cache()
    return torch.cat(chunk_list, dim=1)
    return ajop


def load_nn(net, init_net, layer_idx=0):
    
    count = 0
    # Get the layer_idx+1 th conv layer
    for idx, m in enumerate(net.features):
        if isinstance(m, (P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M, BasicBlock, Bottleneck)):
            count += 1
        if count-1 == layer_idx:
            l_idx = idx
            break

    print("l_idx",l_idx)
    if(isinstance(net.features[l_idx],(P4ConvZ2, P4ConvP4, P4MConvZ2, P4MConvP4M))):
        
        # Construct patchnet
        patchnet = deepcopy(net)
        temp = deepcopy(net.features[l_idx])
        conv_layer = PatchConvLayer(temp)
        
        #Truncate all layers before l_idx    
        patchnet.features = net.features[l_idx:]
        patchnet.features[0] = conv_layer
        
        #layer whose CNFM we need
        layer = deepcopy(net.features[l_idx])
        layer_init = deepcopy(init_net.features[l_idx])     
        
    else:   
        
        # Construct patchnet
        patchnet = deepcopy(net)
        temp_block = deepcopy(net.features[l_idx])
        conv_layer = PatchConvLayer(temp_block.features[0])
        temp_block.features[0]= conv_layer
        if(len(temp_block.shortcut)>0):
           short_layer = PatchConvLayer(temp_block.shortcut[0])
           temp_block.shortcut[0] = short_layer
        else:
           temp_block.shortcut= None
            
        temp_block = PatchBasicBlock(temp_block)
        
        #Truncate all layers before l_idx    
        patchnet.features = net.features[l_idx:]
        patchnet.features[0] = temp_block
        
        #layer whose CNFM we need
        layer = deepcopy(net.features[l_idx].features[0])
        layer_init = deepcopy(init_net.features[l_idx].features[0])        
                
    # Compute WtW which is (c*q*s,c*q*s) matrix
    M = get_nfm(layer)
    M0 = get_nfm(layer_init)

    return net, patchnet, M, M0, l_idx, layer

def get_grads(net, patchnet, trainloader, layer_idx, layer, max_batches=2, classes=10, chunk_size=10, centering=True):
    
    net.eval()
    net.cuda()
    patchnet.eval()
    patchnet.cuda()
    '''
    q, s = kernel
    pad1, pad2 = padding
    s1, s2 = stride
    '''
    M = 0
    ajop = 0
    J_sum=0
    n=0
    
    c = classes
    #Chunking is done to compute jacobian as sum of smaller size matrices using outer product. This saves memory
    chunk = c // chunk_size
    chunk_list = []
    # bs = len(list(trainloader)[0]) 
    bs=128

    for i in range(chunk_size):
        grads = []
        J_sum=0
        print("************* Chunk"+str(i)+"*************")
        for idx, batch in enumerate(trainloader):
            #print("Computing GOP for sample " + str(idx) + \
                  #" out of " + str(max_batches))
            imgs, _ = batch
            #imgs= imgs.double()
            with torch.no_grad():
                imgs = imgs.cuda()     
                imgs = imgs.float()
                # Run the first half of the network wrt to the current layer 
                imgs = net.features[:layer_idx](imgs).cpu() #(bs,c,h,w)
            patches = patchify(imgs, layer)#(bs,w_out,h_out,c,q,s)
            p_copy = deepcopy(patches)
            patches = patches.cuda()
            p_copy = p_copy.cuda()
            c_patches = torch.stack([patches, p_copy], dim=1) #(bs,2,w_out,h_out,c,q,s)
            J = get_jacobian(patchnet, c_patches, c_idx=i, chunk=chunk)
            J= J[:,:,0,:,:,:,:,:]
            bs, c, w, h, _, _, _ = J.shape
            print(J.shape)
            J = J.transpose(1, 3).transpose(1, 2) #(bs, w_out, h_out, chunk, c, q, s)
            J = J.reshape(bs*w*h, c, -1) #(bs*w_out*h_out, chunk, c*q*s)
            if centering:
                J_sum += torch.sum(J, dim=0).unsqueeze(0)  
            J= J.cpu()
            grads.append(J)          
            n += bs         
            #M += egop(patchnet, c_patches, classes, chunk_size).cpu()
            #Js.append(egop(patchnet, c_patches, classes, chunk_size).cpu()) 
            del imgs, patches, p_copy, c_patches, J
            torch.cuda.empty_cache()
            if idx >= max_batches:
                break
       
        if centering:
            J_mean = J_sum*1/(n*w*h) #(1, chunk, c*q*s)
            
        for batch_idx, J in enumerate(grads):
            J = J.cuda()
            if centering:
                J= J- J_mean
            M += torch.einsum('ncd,ncD->dD', J, J).cpu()
            del J
        torch.cuda.empty_cache()
        
    #net.cpu()
    #patchnet.cpu()
    return M*1/n


def verify_NFA(net, init_net, trainloader, layer_idx=0, max_batches=2, classes=10, chunk_size=10, alpha=0.5, centering= True):

    #net = net.double()
    #init_net = init_net.double()
    
    net, patchnet, M, M0, l_idx, layer = load_nn(net, init_net, layer_idx=layer_idx)
    #(q, s), (pad1, pad2), (s1, s2) = conv_vals

    

    G = get_grads(net, patchnet, trainloader, l_idx, 
                 layer, max_batches=max_batches, classes=classes, chunk_size=chunk_size, centering=centering)
    
    print("Shape after gradients: ", G.shape)
    #G = sqrt(G)
    G = matrix_power_eigendecomposition(G, alpha)
    Gop = G.clone()
    
    G = G.cuda()
    M0 = M0.cuda()
    M = M.cuda()
    print("Correlation between Initial and Trained CNFM: ", correlation(M0, M))
    print("Correlation between Initial CNFM and Trained AGOP: ", correlation(M0, G))
    print("Correlation between Trained CNFM and Trained AGOP: ", correlation(M, G))

    del patchnet
    #print("Final: ", i_val, r_val)
    return (Gop, correlation(M, G))
    #return i_val.data.numpy(), r_val.data.numpy()








#TODO: ADD a visualizer for the image

#if __name__ == "__main__":
    #main()

In [15]:
verify_NFA(net, init_net, trainloader, layer_idx=0)


l_idx 0
************* Chunk0*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk1*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk2*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk3*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk4*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk5*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
************* Chunk6*************
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64, 1, 26, 26, 1, 3, 3])
torch.Size([64

(tensor([[ 0.5042,  0.1734, -0.0091,  0.2362,  0.1469, -0.1292, -0.0186, -0.1303,
          -0.2176],
         [ 0.1734,  0.6394,  0.2539, -0.0385,  0.1712, -0.0144, -0.1623, -0.1936,
          -0.1207],
         [-0.0091,  0.2539,  0.5407, -0.1441,  0.1493,  0.1912, -0.2565, -0.1611,
          -0.0098],
         [ 0.2362, -0.0385, -0.1441,  0.6343,  0.1727, -0.1860,  0.1913, -0.0202,
          -0.1453],
         [ 0.1469,  0.1712,  0.1493,  0.1727,  0.9813,  0.1730,  0.1471,  0.1743,
           0.1449],
         [-0.1292, -0.0144,  0.1912, -0.1860,  0.1730,  0.6271, -0.1469, -0.0473,
           0.2279],
         [-0.0186, -0.1623, -0.2565,  0.1913,  0.1471, -0.1469,  0.5453,  0.2662,
          -0.0139],
         [-0.1303, -0.1936, -0.1611, -0.0202,  0.1743, -0.0473,  0.2662,  0.6549,
           0.1767],
         [-0.2176, -0.1207, -0.0098, -0.1453,  0.1449,  0.2279, -0.0139,  0.1767,
           0.5016]]),
 tensor(0.9714, device='cuda:0', dtype=torch.float64, grad_fn=<DivBackward0>))